name: Mannual_workflow123

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'Darshan'
      age:
        description: 'Age'
        type: number
        required: true
jobs:
  Mannual:
    runs-on: ubuntu-latest

    steps:
      - name: Name1
        run: echo "Hi ${{inputs.name}}"

      - name: Age
        run: echo "your age is ${{age}}"

      
