name: Mannual_workflow123

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'Darshan'
jobs:
  Mannual:
    runs-on: ubuntu-latest

    steps:
      - name: Name
        run: echo "Hi ${{inputs.name}}"

      
